# Python - Numpy vectors

In [18]:
import numpy as np
import math as math
import time as time
#권장하지 않는 표기 
a = np.random.randn(5) #가우시안 분포를 따르는 변수값 5개 저장
print(a)

[-0.64138813 -1.43388449  0.33254777  0.14308845  0.71525598]


In [3]:
print(a.shape) # rank가 1인 vector, 열벡터도 행벡터도 아님 

(5,)


In [4]:
print(a.T)  # 결과가 이상하게 나옴 a tansform 랭크가 1인 배열

[ 0.26552783  1.43195868  0.51608644 -0.19000468 -0.05234406]


In [5]:
print(np.dot(a,a.T))  #두 행렬의 곱계산  결과 이상

2.4261975982518136


In [10]:
#권장 
a= np.random.randn(5,1)
print(a)

[[ 2.04137291]
 [-0.76874175]
 [-1.16691372]
 [-0.44992926]
 [ 1.03597147]]


In [8]:
print(a.T)

[[ 0.0389525   0.86925953  1.15733369 -0.04446361  0.97927314]]


In [9]:
 print(np.dot(a,a.T))

[[ 0.0015173   0.03385984  0.04508105 -0.00173197  0.03814514]
 [ 0.03385984  0.75561213  1.00602334 -0.03865042  0.85124251]
 [ 0.04508105  1.00602334  1.33942127 -0.05145924  1.1333458 ]
 [-0.00173197 -0.03865042 -0.05145924  0.00197701 -0.04354202]
 [ 0.03814514  0.85124251  1.1333458  -0.04354202  0.95897588]]


In [20]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [11]:
u = np.zeros((5,1))
print(u)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [19]:
tic = time.time()
for i in range (5):
    u[i]= math.exp(a[i])
toc = time.time()
print(u)
print(str(1000*(toc-tic))+"ms")

tic = time.time()
u=np.exp(a)
toc=time.time()
print(u)
print(str(1000*(toc-tic))+"ms")

[[0.52656098]
 [0.23838113]
 [1.39451651]
 [1.15383185]
 [2.04471001]]
0.1461505889892578ms
[0.52656098 0.23838113 1.39451651 1.15383185 2.04471001]
0.11086463928222656ms


In [28]:
a =np.random.randn(10,1)
b =np.random.randn(10,1)
print(a,b, sep= "\n\n")

[[ 1.89623019]
 [-0.93559173]
 [-0.07362861]
 [ 0.41194898]
 [-0.7086862 ]
 [ 0.03097643]
 [-1.07007095]
 [-0.42826675]
 [ 2.26268636]
 [ 1.00978782]]

[[ 0.28153714]
 [-0.60110753]
 [-1.65125375]
 [-0.02220305]
 [ 0.49686208]
 [ 0.52136662]
 [-0.15854513]
 [-1.09044226]
 [-1.43530106]
 [ 0.67791133]]


In [31]:
c = np.dot(a.T,b)+1
print(c)

[[-0.05372062]]
