# Python - Numpy vectors

In [2]:
import numpy as np

#권장하지 않는 표기 
a = np.random.randn(5) #가우시안 분포를 따르는 변수값 5개 저장
print(a)

[ 0.26552783  1.43195868  0.51608644 -0.19000468 -0.05234406]


In [3]:
print(a.shape) # rank가 1인 vector, 열벡터도 행벡터도 아님 

(5,)


In [4]:
print(a.T)  # 결과가 이상하게 나옴 a tansform 랭크가 1인 배열

[ 0.26552783  1.43195868  0.51608644 -0.19000468 -0.05234406]


In [5]:
print(np.dot(a,a.T))  #두 행렬의 곱계산  결과 이상

2.4261975982518136


In [7]:
#권장 
a = np.random.randn(5,1)
print(a)

[[ 0.0389525 ]
 [ 0.86925953]
 [ 1.15733369]
 [-0.04446361]
 [ 0.97927314]]


In [8]:
print(a.T)

[[ 0.0389525   0.86925953  1.15733369 -0.04446361  0.97927314]]


In [9]:
 print(np.dot(a,a.T))

[[ 0.0015173   0.03385984  0.04508105 -0.00173197  0.03814514]
 [ 0.03385984  0.75561213  1.00602334 -0.03865042  0.85124251]
 [ 0.04508105  1.00602334  1.33942127 -0.05145924  1.1333458 ]
 [-0.00173197 -0.03865042 -0.05145924  0.00197701 -0.04354202]
 [ 0.03814514  0.85124251  1.1333458  -0.04354202  0.95897588]]


In [22]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [20]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)
